name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Increase the patch part of the jar version
        run: |
          echo "Bumping the patch version to $(( "${VERSION}" + 1 ))"
          sed -i -e "s/VERSION=.*/VERSION=${VERSION}.$(( "${VERSION}" + 1 ))/g" pom.xml

      - name: Build the jar
        run: mvn clean install

      - name: Create a release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          body: "This is a release of the simple-java-maven-app project."
