name: Build and push Docker image

on:
  push:
    branches: [ master ]

jobs:
  tag-jar:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.64.0
      with:
        default_bump: patch
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        release_branches: 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        NITIAL_VERSION: 1.0.0

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simple-java-maven-app:${{ steps.tag_version.outputs.new_tag }}

